tactic-limit: 2 #Лимит на количество смены тактик за битву

rebirth-tactic-interval: 40 #Время, через которое игроку присваивается тактика после респавна(в тиках)

spawn-after-loose: #На будущее
  - 0
  - 100
  - 0
